I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/story/act3.rpy", line 272, in script
    scene bg underwater_creature with blinds
  File "game/story/act3.rpy", line 272, in <module>
    scene bg underwater_creature with blinds
NameError: name 'blindslink' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/story/act3.rpy", line 272, in script
    scene bg underwater_creature with blinds
  File "/Users/namseoa/Desktop/renpy-8.1.1-sdk/renpy/ast.py", line 1674, in execute
    paired = renpy.python.py_eval(self.paired)
  File "/Users/namseoa/Desktop/renpy-8.1.1-sdk/renpy/python.py", line 1153, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "/Users/namseoa/Desktop/renpy-8.1.1-sdk/renpy/python.py", line 1146, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/story/act3.rpy", line 272, in <module>
    scene bg underwater_creature with blinds
NameError: name 'blindslink' is not defined

macOS-13.2-arm64-arm-64bit arm64
Ren'Py 8.1.2.23090503
A_Trick_Of_Mind 1.0
Wed Sep 13 23:28:56 2023
