I'm sorry, but an uncaught exception occurred.

While running game code:
TypeError: 'str' object is not callable

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/common/_layout/screen_main_menu.rpym", line 28, in script
    python hide:
  File "/Users/namseoa/Desktop/renpy-8.1.1-sdk/renpy/ast.py", line 1138, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/Users/namseoa/Desktop/renpy-8.1.1-sdk/renpy/python.py", line 1122, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "renpy/common/_layout/screen_main_menu.rpym", line 28, in <module>
    python hide:
  File "renpy/common/_layout/screen_main_menu.rpym", line 35, in _execute_python_hide
    ui.interact()
  File "/Users/namseoa/Desktop/renpy-8.1.1-sdk/renpy/ui.py", line 299, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "/Users/namseoa/Desktop/renpy-8.1.1-sdk/renpy/display/core.py", line 3587, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, pause_modal=pause_modal, **kwargs) # type: ignore
  File "/Users/namseoa/Desktop/renpy-8.1.1-sdk/renpy/display/core.py", line 4543, in interact_core
    rv = renpy.display.focus.mouse_handler(ev, x, y)
  File "/Users/namseoa/Desktop/renpy-8.1.1-sdk/renpy/display/focus.py", line 604, in mouse_handler
    return change_focus(new_focus, default=default)
  File "/Users/namseoa/Desktop/renpy-8.1.1-sdk/renpy/display/focus.py", line 537, in change_focus
    rv = widget.focus(default=default)
  File "/Users/namseoa/Desktop/renpy-8.1.1-sdk/renpy/display/behavior.py", line 993, in focus
    rv = run(self.hovered)
  File "/Users/namseoa/Desktop/renpy-8.1.1-sdk/renpy/display/behavior.py", line 379, in run
    return action(*args, **kwargs)
TypeError: 'str' object is not callable

macOS-13.2-arm64-arm-64bit arm64
Ren'Py 8.1.2.23090503
A Trick Of The Mind 1.0
Sun Sep 24 19:25:06 2023
